name: 👍Like
description: Add a Like
title: "[LIKE]: "
labels: ["like"]
body:
  - type: markdown
    attributes:
      value: |
        Click on `Submit new issue` to validate your like
        Thanks for taking the time
  - type: textarea
    id: like-description
    attributes:
      label: You can say why like
      description: Add something useless if you want, you are free
      placeholder: 
    validations:
      required: false
