name: Mutable like
description: Add a like
title: "Add new like! (mutable)"
labels: ["like-mutable"]
body:
  - type: markdown
    attributes:
      value: |
        Click on `Submit new issue` to validate your like (you could unlike later)
        It is a bit tedious for user but see this as a "like" CSRF protection
  - type: textarea
    id: useless
    attributes:
      label: useless
      description: Add something useless if you want, you are free
      placeholder: 🐛
    validations:
      required: false
