name: ❓Ask your question
description: File a bug report here
title: "[BUG]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time!!!
  - type: textarea
    id: Ask-description
    attributes:
      label: Description the question
      description: Tell us what is your question
    validations:
      required: true
