name: ❓Question
description: your question here
title: "[QUESTION]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Click on `Submit new issue` to validate your question
        Thanks for taking the time
  - type: textarea
    id: Ask-description
    attributes:
      label: Description the question
      description: Tell us what is your question
    validations:
      required: true
