name: Unlike
description: Withdraw my like
title: "I want to Unlike!"
labels: ["unlike-mutable"]
body:
  - type: markdown
    attributes:
      value: |
        Click on `Submit new issue` to unlike a previous like
        It is a bit tedious for user but see this as a "unlike" CSRF protection
  - type: textarea
    id: useless
    attributes:
      label: useless
      description: Add something useless if you want, you are free
      placeholder: 🐛
    validations:
      required: false
