name: 👎Unlike
description: Withdraw my like
title: "[UNLIKE]: "
labels: ["unlike"]
body:
  - type: markdown
    attributes:
      value: |
        Click on `Submit new issue` to unlike a previous like
        Thanks for taking the time
  - type: textarea
    id: unlike
    attributes:
      label: unlike-description
      description: Add something useless if you want, you are free
      placeholder: 
    validations:
      required: false
