name: 👎Unlike
description: Add a unlike
title: "[UNLIKE]: "
labels: ["unlike"]
body:
  - type: markdown
    attributes:
      value: |
        Click on `Submit new issue` to  validate your unlike
        Thanks for taking the time
  - type: textarea
    id: unlike
    attributes:
      label: You can say why unlike
      description: Add something useless if you want, you are free
      placeholder: 
    validations:
      required: false
